#!/usr/bin/env bats
# Tests for scripts/daily_log_status.sh
#
# Validates the per-date classification the xpquest-daily-log skill (Step 2) acts on:
# daily-log state, SR&ED-log state, this host's session count, and the resulting action.
#
# Logs and transcripts are synthesized in a temp dir (OUTPUT_DIR, XPQ_SESSIONS_DIR), so
# the tests never touch the real Daily-Logs folder or ~/.claude transcripts.

SCRIPT="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)/daily_log_status.sh"

DATE="2026-07-11"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

setup() {
  TEST_DIR="$(mktemp -d)"
  export OUTPUT_DIR="$TEST_DIR/logs"
  export XPQ_SESSIONS_DIR="$TEST_DIR/sessions"
  mkdir -p "$OUTPUT_DIR" "$XPQ_SESSIONS_DIR"

  # session_summary.py buckets by local date; pin the zone as its own tests do.
  export TZ="America/Toronto"
}

teardown() {
  rm -rf "$TEST_DIR"
}

# session <name> <date> [text] — a transcript with one human message at local noon on <date>.
session() {
  python3 - "$XPQ_SESSIONS_DIR/$1.jsonl" "$2" "${3:-work on the xpq-org daily log tooling today}" <<'PY'
import json, sys
path, date, text = sys.argv[1:4]
with open(path, "a", encoding="utf-8") as f:
    f.write(json.dumps({
        "timestamp": f"{date}T16:00:00.000Z",
        "type": "user",
        "message": {"content": text},
    }) + "\n")
PY
}

starter_log() {
  cat > "$OUTPUT_DIR/daily_log-$1.md" <<EOF
# XP Quest — Daily Log — $1

## Engineering / R&D

- **xpq-org** #4: something
  - \`abc1234\`: a commit

---
*Session transcripts not included — run \`xpquest-daily-log\` skill manually if needed.*
EOF
}

# enriched_log <date> [sred-section-body]
enriched_log() {
  {
    echo "# XP Quest — Daily Log — $1"
    echo ""
    echo "**Summary:** a day of work."
    echo ""
    echo "## Engineering / R&D"
    echo ""
    echo "- **xpq-org** #4: something"
    if [[ $# -gt 1 ]]; then
      echo ""
      echo "## SR&ED Activity"
      echo ""
      echo "$2"
    fi
    echo ""
    echo "---"
    echo "*Generated by xpquest-daily-log — $1*"
  } > "$OUTPUT_DIR/daily_log-$1.md"
}

# field <name> — value of <name>=... on the first output line.
field() {
  tr '\t' '\n' <<< "${lines[0]}" | sed -n "s/^$1=//p"
}

# ---------------------------------------------------------------------------
# Argument handling
# ---------------------------------------------------------------------------

@test "no arguments exits 1 with usage" {
  run "$SCRIPT"

  [ "$status" -eq 1 ]
  [[ "$output" == *"Usage"* ]]
}

@test "invalid date exits 1 and echoes the bad input" {
  run "$SCRIPT" "not-a-date"

  [ "$status" -eq 1 ]
  [[ "$output" == *"not-a-date"* ]]
}

@test "FROM after TO exits 1" {
  run "$SCRIPT" "2026-07-12" "2026-07-11"

  [ "$status" -eq 1 ]
}

@test "a range prints one line per date, inclusive" {
  run "$SCRIPT" "2026-07-30" "2026-08-02"

  [ "$status" -eq 0 ]
  [ "${#lines[@]}" -eq 4 ]
  [[ "${lines[0]}" == "2026-07-30"$'\t'* ]]
  [[ "${lines[3]}" == "2026-08-02"$'\t'* ]]
}

@test "a single date prints one line" {
  run "$SCRIPT" "$DATE"

  [ "$status" -eq 0 ]
  [ "${#lines[@]}" -eq 1 ]
}

# ---------------------------------------------------------------------------
# Daily-log state and action
# ---------------------------------------------------------------------------

@test "nothing for the date: missing, action none" {
  run "$SCRIPT" "$DATE"

  [ "$(field daily)" = "missing" ]
  [ "$(field sessions)" = "0" ]
  [ "$(field action)" = "none" ]
}

@test "missing daily log with a session on this host: action fresh" {
  session a "$DATE"

  run "$SCRIPT" "$DATE"

  [ "$(field daily)" = "missing" ]
  [ "$(field sessions)" = "1" ]
  [ "$(field action)" = "fresh" ]
}

@test "missing daily log with a git summary: action fresh" {
  echo "# summary" > "$OUTPUT_DIR/github_summary-$DATE.md"

  run "$SCRIPT" "$DATE"

  [ "$(field action)" = "fresh" ]
}

@test "starter log: action fresh" {
  starter_log "$DATE"

  run "$SCRIPT" "$DATE"

  [ "$(field daily)" = "starter" ]
  [ "$(field action)" = "fresh" ]
}

@test "enriched with no sessions on this host: action skip" {
  enriched_log "$DATE"

  run "$SCRIPT" "$DATE"

  [ "$(field daily)" = "enriched" ]
  [ "$(field sred)" = "none" ]
  [ "$(field action)" = "skip" ]
}

@test "enriched with sessions on this host: action merge" {
  enriched_log "$DATE"
  session a "$DATE"
  session b "$DATE"

  run "$SCRIPT" "$DATE"

  [ "$(field sessions)" = "2" ]
  [ "$(field action)" = "merge" ]
}

@test "a message line that looks like a session header is not counted" {
  enriched_log "$DATE"
  session a "$DATE" $'pasted digest output follows\n--- /tmp/other-session.jsonl\nand more text'

  run "$SCRIPT" "$DATE"

  [ "$(field sessions)" = "1" ]
}

@test "sessions on another date are not counted" {
  enriched_log "$DATE"
  session a "2026-07-12"

  run "$SCRIPT" "$DATE"

  [ "$(field sessions)" = "0" ]
  [ "$(field action)" = "skip" ]
}

# ---------------------------------------------------------------------------
# SR&ED-log state
# ---------------------------------------------------------------------------

@test "enriched with a WP pointer and no SR&ED log: gap, action sred" {
  enriched_log "$DATE" "- **WP1** (Semantic Chunking): chunker baseline"

  run "$SCRIPT" "$DATE"

  [ "$(field sred)" = "gap" ]
  [ "$(field action)" = "sred" ]
}

@test "gap with sessions on this host: action merge+sred" {
  enriched_log "$DATE" "- **WP4** (Conversational Augmentation): interview protocol"
  session a "$DATE"

  run "$SCRIPT" "$DATE"

  [ "$(field sred)" = "gap" ]
  [ "$(field action)" = "merge+sred" ]
}

@test "a WP pointer with an SR&ED log present is not a gap" {
  enriched_log "$DATE" "- **WP1** (Semantic Chunking): chunker baseline"
  echo "# sred" > "$OUTPUT_DIR/sred_daily_log-$DATE.md"

  run "$SCRIPT" "$DATE"

  [ "$(field sred)" = "present" ]
  [ "$(field action)" = "skip" ]
}

@test "an SR&ED section that says None is not a gap" {
  enriched_log "$DATE" "None. The day's only issue carries the engineering label."

  run "$SCRIPT" "$DATE"

  [ "$(field sred)" = "none" ]
  [ "$(field action)" = "skip" ]
}

@test "a word that only starts with None is not read as None" {
  enriched_log "$DATE" "Nonetheless, chunker experiments were discussed."

  run "$SCRIPT" "$DATE"

  [ "$(field sred)" = "check" ]
  [ "$(field action)" = "sred" ]
}

@test "None with nothing after it is not a gap" {
  enriched_log "$DATE" "None"

  run "$SCRIPT" "$DATE"

  [ "$(field sred)" = "none" ]
}

@test "an SR&ED section the script cannot classify: check, action sred" {
  enriched_log "$DATE" "Some chunker experiments were discussed."

  run "$SCRIPT" "$DATE"

  [ "$(field sred)" = "check" ]
  [ "$(field action)" = "sred" ]
}

@test "a starter log's SR&ED section is not classified as a gap" {
  starter_log "$DATE"
  printf '\n## SR&ED Activity\n\n- **WP1** (x): y\n' >> "$OUTPUT_DIR/daily_log-$DATE.md"

  run "$SCRIPT" "$DATE"

  [ "$(field daily)" = "starter" ]
  [ "$(field sred)" = "none" ]
  [ "$(field action)" = "fresh" ]
}

# ---------------------------------------------------------------------------
# Read-only
# ---------------------------------------------------------------------------

@test "the script writes nothing to the logs folder" {
  enriched_log "$DATE" "- **WP1** (Semantic Chunking): chunker baseline"
  before=$(ls -la --time-style=full-iso "$OUTPUT_DIR")

  run "$SCRIPT" "$DATE"

  [ "$(ls -la --time-style=full-iso "$OUTPUT_DIR")" = "$before" ]
}
